name: Update Data
on:
  schedule:
    - cron: "0 19-23 * * 3"
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date (in Texas) and define environmental variables
        run: |
          echo "TEXAS_DATE=$(TZ=America/Chicago date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "TEXAS_DATE_ALT=$(TZ=America/Chicago date +%Y%m%d)" >> $GITHUB_ENV
      - name: Fetch 'Accessible Dashboard Data'
        run: wget https://www.dshs.texas.gov/sites/default/files/chs/data/COVID/CaseCountData.xlsx -O AccessibleDashboardData/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Fetch 'Accessible Vaccine Dashboard Data'
        run: wget https://www.dshs.texas.gov/sites/default/files/LIDS-Immunize-COVID19/COVID%20Dashboard/County%20Dashboard/COVID-19%20Vaccine%20Data%20by%20County_$TEXAS_DATE_ALT.xlsx -O AccessibleVaccineDashboardData/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Fetch 'Confirmed Cases over Time by County'
        run: wget https://www.dshs.texas.gov/sites/default/files/chs/data/COVID/Texas%20COVID-19%20Cumulative%20Confirmed%20Cases%20by%20County.xlsx -O ConfirmedCasesOverTimeByCounty/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Fetch 'New Confirmed Cases over Time by County'
        run: wget https://www.dshs.texas.gov/sites/default/files/chs/data/COVID/Texas%20COVID-19%20New%20Confirmed%20Cases%20by%20County.xlsx -O NewConfirmedCasesOverTimeByCounty/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Fetch 'Probable Cases over Time by County'
        run: wget https://www.dshs.texas.gov/sites/default/files/chs/data/COVID/Texas%20COVID-19%20Cumulative%20Probable%20Cases%20by%20County.xlsx -O ProbableCasesOverTimeByCounty/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Fetch 'New Probable Cases over Time by County'
        run: wget https://www.dshs.texas.gov/sites/default/files/chs/data/COVID/Texas%20COVID-19%20New%20Probable%20Cases%20by%20County.xlsx -O NewProbableCasesOverTimeByCounty/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Fetch 'Fatalities over Time by County'
        run: wget https://www.dshs.texas.gov/sites/default/files/chs/data/COVID/Texas%20COVID-19%20Fatality%20Count%20Data%20by%20County.xlsx -O FatalitiesOverTimeByCounty/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Fetch 'Combined Hospital Data over Time by Trauma Service Area (TSA)'
        run: wget https://www.dshs.texas.gov/sites/default/files/chs/data/COVID/Combined%20Hospital%20Data%20over%20Time%20by%20TSA%20Region.xlsx -O HospitalDataOverTimeByTSA/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data Updated
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
