name: Update Data
on:
  schedule:
    - cron: "0 19-23 * * 1,3,5"
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date (in Texas) and define environmental variable
        run: echo "TEXAS_DATE=$(TZ=America/Chicago date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Fetch 'Accessible Dashboard Data'
        run: wget https://www.dshs.state.tx.us/coronavirus/TexasCOVID19CaseCountData.xlsx -O AccessibleDashboardData/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Fetch 'Accessible Vaccine Dashboard Data'
        run: wget https://www.dshs.state.tx.us/immunize/covid19/COVID-19-Vaccine-Data-by-County.xls -O AccessibleVaccineDashboardData/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data Updated
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
