name: Update Case and Fatality Demographics Data
on:
  schedule:
    - cron: "0 12 15 * *"
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date (in Texas) and define environmental variable
        run: echo "TEXAS_DATE=$(TZ=America/Chicago date +%Y-%m-%d)" >> $GITHUB_ENV 
      - name: Fetch 'Case and Fatality Demographics Data'
        run: wget https://dshs.texas.gov/coronavirus/TexasCOVID19Demographics_Counts.xlsx -O CaseAndFatalityDemographicsData/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Case and Fatality Demographics Data Updated
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
