name: Update COVID-19 Vaccine Administration Data by ZIP Code
on:
  schedule:
    - cron: "0 14-23 * * 1"
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date (in Texas) and define environmental variable
        run: echo "TEXAS_DATE=$(TZ=America/Chicago date +%Y-%m-%d)" >> $GITHUB_ENV 
      - name: Fetch 'COVID-19 Vaccine Administration Data by ZIP Code'
        run: wget https://www.dshs.state.tx.us/coronavirus/TexasCOVID19VaccinesbyZIP.xlsx -O VaccineAdministrationByZipCode/$TEXAS_DATE.xlsx
        continue-on-error: true
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: COVID-19 Vaccine Administration Data by ZIP Code Updated
