name: Update Texas Vaccine Provider Data
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date (in Texas) and define environmental variable
        run: echo "TEXAS_DATE=$(TZ=America/Chicago date +%Y-%m-%d)" >> $GITHUB_ENV 
      - name: Fetch 'Texas Vaccine Provider Data'
        run: wget https://genesis.soc.texas.gov/files/accessibility/vaccineprovideraccessibilitydata.csv -O TexasVaccineProviderData/$TEXAS_DATE.csv
        continue-on-error: true
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Texas Vaccine Provider Data Updated
